Spices/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spices.Data;
using Spices.Models;
using Spices.Utilit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Spices.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.manageruser)]  //  lecture7  52:31    وده معناه ان اليوزر كونترولر ده مصرح فقط للرول اللى هو مانجر
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;

        public CategoriesController(ApplicationDbContext db)
        {

            this.db = db;
        }

        //Get
        [HttpGet]

        public async Task<IActionResult> Index()
        {
            var result = await db.Categories.ToListAsync();

            return View(result);
        }


        [HttpGet]
        public IActionResult Create()      // lecture2   minuts
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Category category)    // lecture2  35 minuts
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);

       }


        [HttpGet]     // lecture2  46 minuts
        public async Task<IActionResult> Edit(int? id)    // lecture2  45 minuts
        {
            if(id==null)
            {
                return NotFound();

            }

            var categ = await db.Categories.FindAsync(id);
            if (categ==null)
            {
                return NotFound();
            }
            return View(categ);
        }

        // lecture2  45 minuts
        [HttpPost] // lecture2  53 minuts      
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Edit(Category category)
        {
            if(ModelState.IsValid)
            {
                db.Categories.Update(category);
                 await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


            }
            return View(category);
        }




        [HttpGet]
        public async Task<IActionResult> Delete(int? id)    // lecture2  55 minuts
        {
            if (id == null)
            {
                return NotFound();

            }

            var categ = await db.Categories.FindAsync(id);
            if (categ == null)
            {
                return NotFound();
            }
            return View(categ);
        }




        [HttpPost] // lecture2  59 minuts      
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Category category)
        {
            
                db.Categories.Remove(category);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


        }




        //httpGet  Details method

        [HttpGet]     // lecture2  1:01:35 minuts
        public async Task<IActionResult> Details(int? id)    // lecture2  45 minuts
        {
            if (id == null)
            {
                return NotFound();

            }

            var categ = await db.Categories.FindAsync(id);
            if (categ == null)
            {
                return NotFound();
            }
            return View(categ);
        }
    } 
}

Spices/Areas/Admin/Controllers/CouponsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spices.Data;
using Spices.Models;
using Spices.Utilit;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Spices.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.manageruser)]  //  lecture7  52:31    وده معناه ان اليوزر كونترولر ده مصرح فقط للرول اللى هو مانجر
    [Area("Admin")]    // lecture5       7:46
    public class CouponsController : Controller
    {
        private readonly ApplicationDbContext db;     // lecture5  7 minuts

        public CouponsController(ApplicationDbContext db)
        {
            this.db = db;
        }



        //Get
        [HttpGet]

        public async Task<IActionResult> Index()
        {
            var copuN = await db.Coupons.ToListAsync();

            return View(copuN);
        }

       ////////////START Create///////
        //Get
        [HttpGet]    // lecture5  12 minuts
        public IActionResult Create()
        {


            return View();
        }


        //post
        [HttpPost]        // lecture5  12 minuts
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Create(Coupon cOupon)
        {


            if (ModelState.IsValid)              //lecture5  18:00
            {
                var filEs = HttpContext.Request.Form.Files;      //لما اعمل سممت للفورم هترجع لى ب فايل او بدون فايل  //  هحط الفايل(الصورة) اللى انا حملتها فى الفار اللى اسمه فايل

                if (filEs.Count > 0)
                {

                    byte[]picturE = null;// اعرف اراى او بايت واسميها بيكتيشر 

                    var fs = filEs[0].OpenReadStream();                   //lecture5      //هعرف اوبجكت من نوع استريم واسمه فاييل استريم(اف اس ) علشان يقرأ الفاييل اللى انا حملته)
                    var ms = new MemoryStream();                 //lecture5  20:00    //هعرف اوبجكت من نوع ميمورى استريم واسميه ام اس)
                    fs.CopyTo(ms);           //بنسخ الفاييل اللى انا حملته على الميمورى استريم

                    picturE = ms.ToArray(); //وبحول الميمورى استريم الى اراى   وبكده انا حولت الصورة اللى رفعناها الى اراى اوف بايت زى البروبرتى بيكتيشر الموجوده فى المودل كوبون
                    cOupon.Picture = picturE; 

                }
               

                db.Coupons.Add(cOupon);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                ////////////End Create///////


            }

            return View(cOupon);  //lrecture5  24:00


       
        }

        ///////////////////Start  edit coupon////////////////////////////////////////////////

        // lecture5   28:05:02 minuts   
        //Get
        [HttpGet]
        public async Task<IActionResult> Edit(int? ID)
        { 
            if (ID == null)
            {
                return NotFound();

            }

            var coupOn = await db.Coupons.FindAsync(ID);
            if (coupOn == null)
            {
                return NotFound();  // lecture5   28:00:00minuts
            }
            

            return View(coupOn);
        }



        //post
        [HttpPost]        // lecture5  12 minuts
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon cOupon)
        {


            if (ModelState.IsValid)              //lecture5  
            {
                var filEs = HttpContext.Request.Form.Files;      
                if (filEs.Count > 0)
                {

                    byte[] picturE = null;
                    var fs = filEs[0].OpenReadStream();                  
                    var ms = new MemoryStream();                 //lecture5  
                    fs.CopyTo(ms);          
                    picturE = ms.ToArray();
                    cOupon.Picture = picturE;

                }
                db.Coupons.Update(cOupon);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
            return View(cOupon);  //lrecture5  34:00
       }  /////////////////////////////// End edit coupon//////Get  and Post//////////////////////







        ///////////////////Start  Delete coupon////lecture5///38/////////////////////////////////////////

        // lecture5   38:05:02 minuts   
        //Get
        [HttpGet]
        public async Task<IActionResult> Delete(int? ID)
        {
            if (ID == null)
            {
                return NotFound();

            }

            var coupOn = await db.Coupons.FindAsync(ID);
            if (coupOn == null)
            {
                return NotFound();  // lecture5   00:00:00minuts
            }


            return View(coupOn);
        }



        //post
        [HttpPost]        // lecture5   minuts
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Coupon cOupon)
        {


           
                db.Coupons.Remove(cOupon);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
           
        }  /////////////////////////////// End delte//////Get  and Post//////////////////////

        ///////////////////Start  details coupon////lecture5///41/////////////////////////////////////////

        // lecture5   41:05:02 minuts   
        //Get
        [HttpGet]
        public async Task<IActionResult> Details(int? ID)
        {
            if (ID == null)
            {
                return NotFound();

            }

            var coupOn = await db.Coupons.FindAsync(ID);
            if (coupOn == null)
            {
                return NotFound();  // lecture5   00:00:00minuts
            }


            return View(coupOn);
            ///////////////////end  details coupon////lecture5///41/////////////////////////////////////////
        }

    }
}

Spices/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;  //lecture7  52:29
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;   //lecture7  46:42
using Spices.Data;
using Spices.Utilit;  //lecture7  53:07
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;  //lecture7  46:30
using System.Threading.Tasks;

namespace Spices.Areas.Admin.Controllers
{
    [Authorize(Roles =SD.manageruser)]  //  lecture7  52:31    وده معناه ان اليوزر كونترولر ده مصرح فقط للرول اللى هو مانجر 
    [Area("Admin")]
    public class UsersController : Controller    // lecture7   41:00
    {
        private readonly ApplicationDbContext db;

        public UsersController(ApplicationDbContext db)    //          هنعرف الكونستراكتر لهذا الكونترولر وهنعمل انجيكت للابليكيشن دى بى كونتيكست
        {
            this.db = db;   //initialize
        }



        public async Task<IActionResult> Index()  //lecture7  43:00
        {
            var ClimeSIdentity = (ClaimsIdentity)User.Identity;  //وصار عندى اوبجيكت من نوع كليمز اي دن تيتى  //من خلال الكليمز اى دى اقدر اجيب اليوزر الحالى اللى عامل لوج ان
            var ClaimM = ClimeSIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string UserID = ClaimM.Value;
            return View(await db.ApplicationUsers.Where(m => m.Id != UserID).ToListAsync());



        }

        public async Task<IActionResult> LockUNlock(string? iD)  //lecture7  01:29:40
        {
            if(iD==null)
            {
                return NotFound();
            }
            var usEr = await db.ApplicationUsers.FindAsync(iD);   ////lecture7  01:30:27

            if (usEr==null)
            {
                return NotFound();
            }

            if(usEr.LockoutEnd==null ||usEr.LockoutEnd<DateTime.Now)   //lecture7  01:31:27     هفحص لو 
            {

                usEr.LockoutEnd = DateTime.Now.AddYears(1000);   //  اغلق حسابه

            }
            else 
            {
                usEr.LockoutEnd = DateTime.Now;                //افتح حسابه     lecture7  01:33:00   
            }
           
                await db.SaveChangesAsync();                      //علشان يعمل اب ديت لهذه البروبرتى فى جدول  الايه اس بى يوزرز    

                return RedirectToAction(nameof(Index));     //lecture7  01:34:03

        }

    }
}
 //   \  | 

Spices/Areas/Customer/Controllers/CartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Spices.Data;
using Spices.Models;
using Spices.Models.ViewModels;
using Spices.Utilit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Spices.Areas.Customer.Controllers
{
    [Area("Customer")] // lecture9   30:39
    [Authorize]
    public class CartsController : Controller  //lecture9 00:19:00
    {
        private readonly ApplicationDbContext db;     // lecture9   minuts

        public CartsController(ApplicationDbContext db)
        {
            this.db = db;
        }

        [BindProperty]   //اتربيوت بيند بروبرتى  lecture 9  20:00
        public OrderDetailsCartViewModel OrderDetailsCartVM { get; set; }




        public IActionResult Index()
        {          
            
                OrderDetailsCartVM = new OrderDetailsCartViewModel()   //initialize  lecture 9   21:20
                {
                    orderHeader = new Models.OrderHeader()  //set for some property    lecture 9   21:20 

                };

            OrderDetailsCartVM.orderHeader.OrderTotal = 0;                       //lecture9 22:25

            var ClimeSIdentity = (ClaimsIdentity)User.Identity;  //lecture8 1:12:00وصار عندى اوبجيكت من نوع كليمز اي دن تيتى  //من خلال الكليمز اى دى اقدر اجيب اليوزر الحالى اللى عامل لوج ان
            var ClaimM = ClimeSIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var shoppingcArts = db.ShoppingCarts.Where(c =>c.ApplicationUsErId == ClaimM.Value);  //lecture9 25:00  take care==>>     ApplicationUseR.Id    علشان ارجع الايتم اللى موجوده فى الشوبينج كارت
            if (shoppingcArts !=null)  // not equal null 
            {
                  
                OrderDetailsCartVM.ShoppingCarTSlist = shoppingcArts.ToList();   //lecture9 25:56    we make her asign for property number2

            }
            foreach (var iteM in OrderDetailsCartVM.ShoppingCarTSlist)
            {

                iteM.MenIteM = db.MenuItems.FirstOrDefault(m => m.ID == iteM.MenuIteMId);  //lecture9   27:45   FirstOrDefault== where     & we make her asign for property MenIteM
                OrderDetailsCartVM.orderHeader.OrderTotal += iteM.MenIteM.Price * iteM.CouNt ;

                iteM.MenIteM.description = SD.ConvertToRawHtml(iteM.MenIteM.description);   //lecture9   44:19
              
               /* if(iteM.MenIteM.description.Length>75)
                {
                    iteM.MenIteM.description = iteM.MenIteM.description.Substring(0, 70);   //lecture9   46:19

                }*/
            
            
            }

            OrderDetailsCartVM.orderHeader.OrderTotalOrginal = OrderDetailsCartVM.orderHeader.OrderTotal;
            return View(OrderDetailsCartVM);   //lecture9 30:00   
        }
    }
}

Spices/Views/Shared/_CreateAndBackToListButtonPartial.cshtml
<div class="row">    <!--lecture2 00minuts-->
    <div class="col-6">
        <input type="submit" class="btn btn-primary form-control " value="create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spices/Views/Shared/_CreateButtonPartail.cshtml
<a class="btn btn-primary" asp-action="Create"><i class="fas fa-plus"></i> &nbsp; Create New</a>

Spices/Views/Shared/_DeleteAndBackToListButtonPartial.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control " value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spices/Views/Shared/_EditAndBackToListButtonPartial.cshtml
<div class="row">   <!--lecture2 1:04:02minuts-->
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-primary form-control " >Edit</a>    
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spices/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http   <!--Lecture8    1:13:00-->    <!--وهعمل انجيكت لسيرفيز اسمها   IHttpContextAccessor وهعرف منها اوبجيكت-->
@inject IHttpContextAccessor HTTPHttpContextAccessoR

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spices</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!--manual download fontawsome lactcure2  farag -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="webBackGround">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <!--lecture7   01:41:00-->
                    @*<img src="~/images/greenpepper.jpg" width="25px" />      lecture7   01:42:00
                        <img src="~/images/Mild.jpg" width="25px" />*@
                    <label class="text-info" style="cursor:pointer;">
                        <!--lecture7   01:41:00-->
                        Spices
                    </label>                                                   <!--lecture7   01:41:00-->


                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>    //lecture7 01:04:00
                                            </li>
                                            @*<li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>      //lecture7 01:04:00
                            </li>*@


                        @if (User.IsInRole(SD.manageruser))      //<!--lecture7  01:39:37   الدروب داون ليست هتظهر للرول اللى واخده مانيجر-->
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Managment
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-action="index" asp-controller="Categories" asp-area="Admin"> Category</a>
                                    <a class="dropdown-item" asp-action="index" asp-controller="SubCategories" asp-area="Admin">Sub Category</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-action="index" asp-controller="MenuItems" asp-area="Admin">Menu Item</a>     <!--LECTURE 4    22:15-->
                                    <a class="dropdown-item" asp-action="index" asp-controller="Coupons" asp-area="Admin">Coupons</a>  <!--Lecture5   11 minuts-->
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-action="index" asp-controller="Users" asp-area="Admin">Users</a>     <!--Lecture7  56:34 minuts-->
                                </div>
                            </li>
                        }

                        @if (HTTPHttpContextAccessoR.HttpContext.Session.GetInt32(SD.shoppingcartcount) == null)// lecture8  1:14:00
                        {
                            <li class="nav-item">
                                <!--lecture7   01:44:00-->

                                <a href="#" class="text-white" style="text-decoration:none">
                                    <i class="fa-solid fa-cart-shopping"></i>&nbsp;(0)  <!--lecture7   01:46:20-->
                                    @* <i class="fas-fa-shopping-cart"></i>  &nbsp;(0)    =>>>>  &nbsp; =>>    nullable space *@
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <!--lecture8   01:14:00-->

                                <a asp-action="Index" asp-controller="Carts" asp-area="Customer" class="text-white" style="text-decoration:none">
                                    <i class="fa-solid fa-cart-shopping"></i>&nbsp;(@HTTPHttpContextAccessoR.HttpContext.Session.GetInt32(SD.shoppingcartcount))
                                    @* <i class="fas-fa-shopping-cart"></i>  &nbsp;(0)    =>>>>  &nbsp; =>>    nullable space *@
                                </a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-dark">
        <div class="container">
            &copy; 2022 - Spices - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/1o0aj3m12pj3xd5u8sxp9015irpcdclb0jgvaikdfpus0veg/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script> <!--محاضره4 الدقيقه 1:11:00 بيشرح فيها موقع تينى دوت كلاوود الخاص بالريتش تيكسيت بوكس-->
    @RenderSection("Scripts", required: false)
</body>
</html>

Spices/Views/Shared/_OperationsButtonPartial.cshtml
@model int     
<div class="btn-group" role="group">
    <a asp-action="Details" class="btn btn-success text-white" asp-route-id="@Model">    <!--lecture2 52 minuts-->

        <i class="fas fa-list-alt"></i>
    </a>
    <a asp-action="Edit" class="btn btn-primary text-white" asp-route-id="@Model">

        <i class="fas fa-edit"></i>            <!--  // <i class="fa-duotone fa-pen-to-square-"></i> //   //<i class="fa-light fa-pen-to-square"></i>// -->
    </a>
    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model">

        <i class="fa-solid fa-trash-alt"></i>
    </a>

</div>

Spices/Views/Shared/_UpdateAndBackToListButtonPartial.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-primary form-control " value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>